sudo: required
dist: trusty
language: php
php:
  - 7.1
  - 7.2
  - 7.3

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - libxml2-utils
  sauce_connect: true

services:
- postgresql

env:
  global:
  - CORE_BRANCH=master
  - DB=sqlite
  - PHP_COVERAGE=FALSE
  - TEST_JS=FALSE
  - SAUCE=FALSE
  matrix:
  - DB=sqlite

branches:
  only:
  - master
  - "/^stable\\d+(\\.\\d+)?$/"
  - /^v\d++(\.\d+)?+(\.\d+)?+(\.\d+)?$/

cache:
  directories:
  - "$HOME/.composer/cache/files"
  - "$HOME/.npm"

before_install:
  - php --info

  # XDebug is only needed if we report coverage -> speeds up other builds (7.3 has no xdebug yet)
  - if [[ "$PHP_COVERAGE" = "FALSE" ]]; then phpenv config-rm xdebug.ini || true; fi

  # Set up DB
  - if [[ "$DB" == 'pgsql' ]]; then createuser -U travis -s nc_autotest; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e 'create database nc_autotest;'; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "CREATE USER 'nc_autotest'@'localhost' IDENTIFIED BY '';"; fi
  - if [[ "$DB" == 'mysql' ]]; then mysql -u root -e "GRANT ALL ON nc_autotest.* TO 'nc_autotest'@'localhost';"; fi

  - composer self-update
  - composer install
  - npm install

  # Set up Apache + php-fpm for acceptance tests
  - if [[ "$SAUCE" = "TRUE"  ]]; then ./ci/setup_apache_travis.sh; fi

  - cd ..
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH core
  - mv twofactor_totp core/apps/

before_script:
  # Set up core
  - php -f core/occ maintenance:install --database-name nc_autotest --database-user nc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''

  # Enable debug mode to get more info in case a test fails
  - php -f core/occ config:system:set debug --value=true --type boolean

  # Set up app
  - php -f core/occ app:enable twofactor_totp
  - cd core/apps/twofactor_totp

script:
  # Check info.xml schema validity
  - wget https://apps.nextcloud.com/schema/apps/info.xsd
  - xmllint appinfo/info.xml --schema info.xsd --noout
  - rm info.xsd

  # Build js bundle
  - npm run build

  # Run js tests
  - if [[ "$TEST_JS" = "TRUE" ]]; then npm run test; fi

  # Lint php files
  - if [[ "$SAUCE" = "FALSE" ]]; then find . -name \*.php -not -path './vendor/*' -exec php -l "{}" \;; fi

  # Run php unit tests
  - if [[ "$SAUCE" = "FALSE" ]]; then ./vendor/bin/phpunit --fail-on-warning --configuration tests/phpunit.xml --group default; fi
  - if [[ "$SAUCE" = "TRUE"  ]]; then ./vendor/bin/phpunit --fail-on-warning --configuration tests/phpunit.xml --group Acceptance --no-coverage; fi
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$PHP_COVERAGE" = "TRUE" ]]; then php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml; fi

matrix:
  include:
    - php: 7.1
      env: "DB=pgsql PHP_COVERAGE=TRUE"
    - php: 7.2
      env: "DB=mysql"
    - php: 7.2
      env: "TEST_JS=TRUE"
    - php: 7.2
      env: "DB=mysql SAUCE=TRUE SELENIUM_BROWSER=firefox"
    - php: 7.2
      env: "DB=mysql SAUCE=TRUE SELENIUM_BROWSER=chrome"
    - php: 7.1
      env: "DB=mysql CORE_BRANCH=stable15"
    - php: 7.1
      env: "DB=mysql CORE_BRANCH=v15.0.0"
  fast_finish: true

